// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice =
  | HeroWithBackgroundImageSlice
  | NotificationBarSlice
  | IconCardGridSlice
  | TestimonialCardsWithImageSlice
  | CenteredCtaSlice
  | ContentHighlightWithImageSlice
  | FeatureGridSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = HomeDocument;

/**
 * Primary content in *CenteredCta → Single Button → Primary*
 */
export interface CenteredCtaSliceSingleButtonPrimary {
  /**
   * Button Link field in *CenteredCta → Single Button → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_cta.single_button.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Background Color field in *CenteredCta → Single Button → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_cta.single_button.primary.button_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_background_color: prismic.ColorField;
}

/**
 * Single Button variation for CenteredCta Slice
 *
 * - **API ID**: `single_button`
 * - **Description**: Displays a single button centered within a colored background.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CenteredCtaSliceSingleButton = prismic.SharedSliceVariation<
  "single_button",
  Simplify<CenteredCtaSliceSingleButtonPrimary>,
  never
>;

/**
 * Slice variation for *CenteredCta*
 */
type CenteredCtaSliceVariation = CenteredCtaSliceSingleButton;

/**
 * CenteredCta Shared Slice
 *
 * - **API ID**: `centered_cta`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CenteredCtaSlice = prismic.SharedSlice<
  "centered_cta",
  CenteredCtaSliceVariation
>;

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface ContentHighlightWithImageSliceDefaultPrimary {
  /**
   * Title field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: content_highlight_with_image.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_highlight_with_image.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content_highlight_with_image.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Main Image field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_highlight_with_image.default.primary.main_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<"mobile">;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard layout with a prominent content box alongside an image.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentHighlightWithImageSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<ContentHighlightWithImageSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *CallToAction*
 */
type ContentHighlightWithImageSliceVariation =
  ContentHighlightWithImageSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `content_highlight_with_image`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentHighlightWithImageSlice = prismic.SharedSlice<
  "content_highlight_with_image",
  ContentHighlightWithImageSliceVariation
>;

/**
 * Item in *News → Grid → Primary → Main Feature*
 */
export interface FeatureGridSliceMainWithCardGridAndActionPrimaryMainFeatureItem {
  /**
   * Image field in *News → Grid → Primary → Main Feature*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.main_with_card_grid_and_action.primary.main_feature[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Headline field in *News → Grid → Primary → Main Feature*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.main_with_card_grid_and_action.primary.main_feature[].headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.TitleField;

  /**
   * News link field in *News → Grid → Primary → Main Feature*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.main_with_card_grid_and_action.primary.main_feature[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *News → Grid → Primary → Feature Cards*
 */
export interface FeatureGridSliceMainWithCardGridAndActionPrimaryFeatureCardsItem {
  /**
   * Title field in *News → Grid → Primary → Feature Cards*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.main_with_card_grid_and_action.primary.feature_cards[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *News → Grid → Primary → Feature Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.main_with_card_grid_and_action.primary.feature_cards[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Card Link field in *News → Grid → Primary → Feature Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.main_with_card_grid_and_action.primary.feature_cards[].card_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  card_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *News → Grid → Primary*
 */
export interface FeatureGridSliceMainWithCardGridAndActionPrimary {
  /**
   * Main Feature field in *News → Grid → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.main_with_card_grid_and_action.primary.main_feature[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  main_feature: prismic.GroupField<
    Simplify<FeatureGridSliceMainWithCardGridAndActionPrimaryMainFeatureItem>
  >;

  /**
   * Feature Cards field in *News → Grid → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.main_with_card_grid_and_action.primary.feature_cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  feature_cards: prismic.GroupField<
    Simplify<FeatureGridSliceMainWithCardGridAndActionPrimaryFeatureCardsItem>
  >;
}

/**
 * Grid variation for News Slice
 *
 * - **API ID**: `main_with_card_grid_and_action`
 * - **Description**: Displays a main featured item with image and large headline, to the left; a supporting grid or list of additional features to the right, and an optional prominent action button overlay above the content.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureGridSliceMainWithCardGridAndAction =
  prismic.SharedSliceVariation<
    "main_with_card_grid_and_action",
    Simplify<FeatureGridSliceMainWithCardGridAndActionPrimary>,
    never
  >;

/**
 * Slice variation for *News*
 */
type FeatureGridSliceVariation = FeatureGridSliceMainWithCardGridAndAction;

/**
 * News Shared Slice
 *
 * - **API ID**: `feature_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureGridSlice = prismic.SharedSlice<
  "feature_grid",
  FeatureGridSliceVariation
>;

/**
 * Primary content in *HeroWithBackgroundImage → Default → Primary*
 */
export interface HeroWithBackgroundImageSliceDefaultPrimary {
  /**
   * Background Image field in *HeroWithBackgroundImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_background_image.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<"mobile" | "tablet">;

  /**
   * Title field in *HeroWithBackgroundImage → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_background_image.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *HeroWithBackgroundImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_background_image.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for HeroWithBackgroundImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero with prominent title, description, and background image for immediate context.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroWithBackgroundImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroWithBackgroundImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroWithBackgroundImage*
 */
type HeroWithBackgroundImageSliceVariation =
  HeroWithBackgroundImageSliceDefault;

/**
 * HeroWithBackgroundImage Shared Slice
 *
 * - **API ID**: `hero_with_background_image`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroWithBackgroundImageSlice = prismic.SharedSlice<
  "hero_with_background_image",
  HeroWithBackgroundImageSliceVariation
>;

/**
 * Item in *IconCardGrid → Default → Primary → Cards*
 */
export interface IconCardGridSliceDefaultPrimaryCardsItem {
  /**
   * Icon field in *IconCardGrid → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_card_grid.default.primary.cards[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Link field in *IconCardGrid → Default → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_card_grid.default.primary.cards[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *IconCardGrid → Default → Primary*
 */
export interface IconCardGridSliceDefaultPrimary {
  /**
   * Cards field in *IconCardGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_card_grid.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<Simplify<IconCardGridSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for IconCardGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard grid where each card displays an icon, label, and optional link for primary actions.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconCardGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IconCardGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IconCardGrid*
 */
type IconCardGridSliceVariation = IconCardGridSliceDefault;

/**
 * IconCardGrid Shared Slice
 *
 * - **API ID**: `icon_card_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconCardGridSlice = prismic.SharedSlice<
  "icon_card_grid",
  IconCardGridSliceVariation
>;

/**
 * Primary content in *NotificationBar → Default → Primary*
 */
export interface NotificationBarSliceDefaultPrimary {
  /**
   * Message field in *NotificationBar → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: notification_bar.default.primary.message
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  message: prismic.RichTextField;

  /**
   * Background Color field in *NotificationBar → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: notification_bar.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;
}

/**
 * Default variation for NotificationBar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard notification bar with message and single call-to-action link.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NotificationBarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NotificationBarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NotificationBar*
 */
type NotificationBarSliceVariation = NotificationBarSliceDefault;

/**
 * NotificationBar Shared Slice
 *
 * - **API ID**: `notification_bar`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NotificationBarSlice = prismic.SharedSlice<
  "notification_bar",
  NotificationBarSliceVariation
>;

/**
 * Item in *Stories → Default → Primary → Cards*
 */
export interface TestimonialCardsWithImageSliceDefaultPrimaryCardsItem {
  /**
   * Image field in *Stories → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_cards_with_image.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Headline field in *Stories → Default → Primary → Cards*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_cards_with_image.default.primary.cards[].headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.TitleField;

  /**
   * Description field in *Stories → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_cards_with_image.default.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link field in *Stories → Default → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_cards_with_image.default.primary.cards[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Stories → Default → Primary*
 */
export interface TestimonialCardsWithImageSliceDefaultPrimary {
  /**
   * Cards field in *Stories → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_cards_with_image.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<
    Simplify<TestimonialCardsWithImageSliceDefaultPrimaryCardsItem>
  >;
}

/**
 * Default variation for Stories Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard layout with image, headline, and body text side by side, supporting multiple items.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialCardsWithImageSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<TestimonialCardsWithImageSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *Stories*
 */
type TestimonialCardsWithImageSliceVariation =
  TestimonialCardsWithImageSliceDefault;

/**
 * Stories Shared Slice
 *
 * - **API ID**: `testimonial_cards_with_image`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialCardsWithImageSlice = prismic.SharedSlice<
  "testimonial_cards_with_image",
  TestimonialCardsWithImageSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      CenteredCtaSlice,
      CenteredCtaSliceSingleButtonPrimary,
      CenteredCtaSliceVariation,
      CenteredCtaSliceSingleButton,
      ContentHighlightWithImageSlice,
      ContentHighlightWithImageSliceDefaultPrimary,
      ContentHighlightWithImageSliceVariation,
      ContentHighlightWithImageSliceDefault,
      FeatureGridSlice,
      FeatureGridSliceMainWithCardGridAndActionPrimaryMainFeatureItem,
      FeatureGridSliceMainWithCardGridAndActionPrimaryFeatureCardsItem,
      FeatureGridSliceMainWithCardGridAndActionPrimary,
      FeatureGridSliceVariation,
      FeatureGridSliceMainWithCardGridAndAction,
      HeroWithBackgroundImageSlice,
      HeroWithBackgroundImageSliceDefaultPrimary,
      HeroWithBackgroundImageSliceVariation,
      HeroWithBackgroundImageSliceDefault,
      IconCardGridSlice,
      IconCardGridSliceDefaultPrimaryCardsItem,
      IconCardGridSliceDefaultPrimary,
      IconCardGridSliceVariation,
      IconCardGridSliceDefault,
      NotificationBarSlice,
      NotificationBarSliceDefaultPrimary,
      NotificationBarSliceVariation,
      NotificationBarSliceDefault,
      TestimonialCardsWithImageSlice,
      TestimonialCardsWithImageSliceDefaultPrimaryCardsItem,
      TestimonialCardsWithImageSliceDefaultPrimary,
      TestimonialCardsWithImageSliceVariation,
      TestimonialCardsWithImageSliceDefault,
    };
  }
}
